### ISSUE TITLE
Strength bars not showing in Chrome desktop or Firefox Android.

### ISSUE THREAD

**Issue by masumshaikh** [ToranSharma/Duo-Strength#33] opened 2020-01-28 22:20 UTC
Desktop: when I first load the web page, I do not see any strength bars. After I test out of a skill, they do appear (and will continue to do so even if I load Duolingo.com in a new tab, until I exit Chrome entirely).

Android: have not yet fully tested behaviour.

**Comment by ToranSharma** [comment] 2020-01-28 22:44
Hi @masumshaik,  

Thanks for reporting this issue.

I have seen the behaviour you describe in any of the accounts I have access to. Can you give any more details about which language tree are you seeing this issue with, does it happen with any others?

If possible, sending a screenshot or pasting any errors in the console would be very useful to help solve this issue.

In Chrome on desktop, you can open this by right clicking anyway on the duolingo learn page, and selecting inspect.  
![Inspect Context Menu Item](https://toransharma.com/i/inspect%20context%20menu%20item.png)

Then from the window that appears, you can click the console tab in the top left.
![Console Tab](https://toransharma.com/i/console%20tab.png)

If you could send a screenshot or, copy and paste any errors that would be great.

Thanks,

Toran

**Comment by masumshaikh** [comment] 2020-01-29 12:12
[Image]

[Image]

Hi,

I can't reproduce the issue on Chrome desktop any more either.

On Mozilla Android, I still have the issue on the mobile page (which I didn't before) but see the correct behaviour when I request the desktop version of the page. Hope this helps, but I'm happy for the issue to be closed either way.


Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by ToranSharma** [comment] 2020-01-29 12:21
Its a strange one, I can't think of a reason for the different behaviour and cannot reproduce it myself on Firefox for Android either.

Unfortunately, your images did not attach to the message properly, its probably an email reply thing. If you are able to, on desktop you can drag images in, or insert them with image markdown syntax.

**Comment by ToranSharma** [comment] 2020-03-31 20:37
I have still yet to encounter this and as such I am going to close this issue now. Please feel free to reopen it if you do find a way to reproduce the issue.

Thanks,

Toran

**Closed by ToranSharma** 2020-03-31 20:37 UTC
