### ISSUE TITLE
Flag border did not update. 

### ISSUE THREAD

**Issue by alexseyk** [ToranSharma/Duo-Strength#117] opened 2020-10-28 08:05 UTC
FYI: Flag border did not update after i got to L3 in Latin. Same after i cleaned browser data in chrome.

**Comment by ToranSharma** [comment] 2020-10-28 16:03
Is it still showing the L2 coloured border or just nothing at all?

If possible could you run this command in the console and let me know the output:
```javascript
chrome.storage.sync.get("progress", (data) => Object.keys(data.progress).forEach((tree) => console.log(`${tree} is at tree level ${data.progress[tree][data.progress[tree].length -1][1]}`)))
```
It should give a list of all the trees that have progress history saved and spit out the last known tree level. Note you need to change to the Duo Strength execution context first:
![image](https://user-images.githubusercontent.com/4559968/97461637-d6a48780-1935-11eb-80fc-467e42246502.png)

**Comment by ToranSharma** [comment] 2020-10-28 21:21
I think I might have an idea of what could cause this if it is still showing level 2 and that command returns level 2.

If you run
```javascript
currentTreeLevel()
```
it will return what is being calculated based on the user data file is your current tree level, i,e. the minimum crown level of any skill in your tree.

If your Latin tree has recently been updated to add grammar skills, then these skills only go up to level 2 and the currentTreeLevel function will count this as the minimum level of a skill in your tree.

I will fix this now quickly as v1.3.38.

**Comment by ToranSharma** [comment] 2020-10-28 21:55
v1.3.38 has now been released,

Let me know if this fixes it.

If not then the output of the functions in the above would be appriciated.

Toran

**Comment by alexseyk** [comment] 2020-10-29 02:16
Hi
It still shows a L2 color border 
 
after running the command  see log 1 
[log1.log](https://github.com/ToranSharma/Duo-Strength/files/5455683/log1.log)

currentTreeLevel says 3 and it is also says so in the Crowns info, as before .

May be you need a way to clean the log from data in old storage format 
PS . My profile his set to private (if that matters)

**Comment by ToranSharma** [comment] 2020-10-29 10:47
Thanks for the information. It is a little difficult to see which of those is the relevant line, I wasn't expecting so much output! To get the relevant entry, could you run this command while on the Latin tree in question:
```javascript
`${username}(ID:${userId}) ${UICode}->${languageCode} last progress entry:[${progress.slice(-1)}] (${progress.length} entries)`
```

Because you are still seeing the L2 colour border, I have to assume that this will give tree level 2 as the second field in the last progress entry. It is interesting that the currentTreeLevel function is outputting the correct level as 3, so this should be getting saved into the progress.

I am still not exactly sure what impact the public/private profile setting has on any of Duo Strength's features. As long as the userData file is able to downloaded properly

NB: I had only briefly considered that users can change their username. As you have seen from the output, the trees are saved by the username with the tree languages appended. So any time the user changes their username it makes a new entry to save their progress.

A better solution would be to use their Duolingo user id which I assume does not change. I will add this to my to do list.

**Comment by alexseyk** [comment] 2020-10-29 11:46
userscript.html?name=Duolingo%20Tree%20Enhancer.user.js&id=288310d7-a2ee-4548-833e-5e998733192f:1666 Updated Setup {"":"","autoplay":true,"enableMicrophone":false,"enableSpeaker":true}
`${username}(ID:${userId}) ${UICode}->${languageCode} last progress entry:[${progress.slice(-1)}] (${progress.length} entries)`
"AKS-47(ID:33917959) en->la last progress entry:[1603904400000,3,29] (15 entries)"

**Comment by ToranSharma** [comment] 2020-10-29 12:15
Well the last recorded entry for your tree is for level 3:  
> [1603904400000,**3**,29]

So every is being saved and recalled correctly. I can think of s reason why it would show up as being at level 2. I'll have a look at the code and see if I can find a mistake.

**Comment by alexseyk** [comment] 2020-10-29 12:22
<img width="456" alt="Screen Shot 2020-10-29 at 19 21 49" src="https://user-images.githubusercontent.com/60418150/97573268-0fb72780-1a1c-11eb-9b6c-7790112a7be3.png">

**Comment by alexseyk** [comment] 2020-10-29 12:25
but the log says it is L2 
AKS-47la is at tree level 0 VM187:1 
AKS-47laen is at tree level 2 VM187:1

**Comment by ToranSharma** [comment] 2020-10-29 12:31
Yeah, I was just writing a message saying that it is strange that your first log doesn't match the others. There is a chance that it isn't being saved correctly then.

**Comment by ToranSharma** [comment] 2020-10-29 12:36
If you run this it will give the last few saved entries for your Latin tree:
```javascript
chrome.storage.sync.get("progress", data => console.log(data.progress[username+"laen"]. slice (-3)))
```

**Comment by alexseyk** [comment] 2020-10-29 12:48
Ok. there is a lot. Hope you can make out what that means. 
[www.duolingo.com-1603975651264.log](https://github.com/ToranSharma/Duo-Strength/files/5458405/www.duolingo.com-1603975651264.log)

**Comment by ToranSharma** [comment] 2020-10-29 12:55
Sorry that didn't work as intended (I should have tried it first but was only on my phone).

This is what it should have been:
```javascript
chrome.storage.sync.get("progress", data => data.progress[username+"laen"]. slice(-3).forEach(entry => console.log(entry)))
```

Sorry about all this back and forth.

**Comment by alexseyk** [comment] 2020-10-29 12:59
NP. Still ...  it looks like the same array of data.
[www.duolingo.com-1603976299625.log](https://github.com/ToranSharma/Duo-Strength/files/5458451/www.duolingo.com-1603976299625.log)

**Comment by ToranSharma** [comment] 2020-10-29 13:17
It's a bit of a mess but I can see what I needed:
[1588611600000, 2, 48]
[1588611600000, 2, 48]
[1589734800000, 2, 29]

The last entry there is from May 17 2020 18:00:00 GMT+0100 showing that your tree was at level 2 with 29 lessons until the next treeLevel.

This clearly isn't correct as a previous command you ran gave
[1603904400000,3,29] which is from today at level 3 with 29 lesson to go. This was from the 'live' copy of the current trees progress that is kept in memory while the script is running.

So it seems like these new entries are not being stored for some reason.

**Comment by ToranSharma** [comment] 2020-10-29 13:26
One last command just to compare a bit more data, the output should be formatted a bit more nicely this time.
It needs to be run while on the latin tree:
```javascript
chrome.storage.sync.get("progress", data => {d = data.progress[username+"laen"]; console.log(`from storage: ${d.length} entries`); d.slice(-5).forEach(entry => console.log(`[${entry}]`));}); console.log(`from memory: ${progress.length} entries`); progress.slice(-5).forEach(entry=>console.log(`[${entry}]`));
```

**Comment by alexseyk** [comment] 2020-10-29 13:31
so the same for russian 
<img width="461" alt="Screen Shot 2020-10-29 at 20 24 37" src="https://user-images.githubusercontent.com/60418150/97579669-e949ba00-1a24-11eb-895f-03eecb996c16.png">

`${username}(ID:${userId}) ${UICode}->${languageCode} last progress entry:[${progress.slice(-1)}] (${progress.length} entries)`
"ak-s(ID:30016311) en->ru last progress entry:[1603904400000,1,347] (1 entries)"

**Comment by ToranSharma** [comment] 2020-10-29 13:35
> so the same for russian
> <img alt="Screen Shot 2020-10-29 at 20 24 37" width="461" src="https://user-images.githubusercontent.com/60418150/97579669-e949ba00-1a24-11eb-895f-03eecb996c16.png">
> 
> `${username}(ID:${userId}) ${UICode}->${languageCode} last progress entry:[${progress.slice(-1)}] (${progress.length} entries)`
> "ak-s(ID:30016311) en->ru last progress entry:[1603904400000,1,347] (1 entries)"

This is strange, again, the progress entry that is saved in memory there is showing Level 1, and the crowns info box agrees, but the data that the flag borders use is the saved progress doesn't have any data so it showing level 0 there as it is the default.

**Comment by alexseyk** [comment] 2020-10-29 13:36
and now for Latin 

chrome.storage.sync.get("progress", data => {d = data.progress[username+"laen"]; console.log(`from storage: ${d.length} entries`); d.slice(-5).forEach(entry => console.log(`[${entry}]`));}); console.log(`from memory: ${progress.length} entries`); progress.slice(-5).forEach(entry=>console.log(`[${entry}]`));
VM1316:1 from memory: 15 entries
VM1316:1 [1588525200000,1,4]
VM1316:1 [1588611600000,2,48]
VM1316:1 [1588611600000,2,48]
VM1316:1 [1589734800000,2,29]
VM1316:1 [1603904400000,3,29]
undefined
VM1316:1 from storage: 14 entries
VM1316:1 [1588438800000,1,10]
VM1316:1 [1588525200000,1,4]
VM1316:1 [1588611600000,2,48]
VM1316:1 [1588611600000,2,48]
VM1316:1 [1589734800000,2,29]

**Comment by alexseyk** [comment] 2020-10-29 13:42
> This is strange, again, the progress entry that is saved in memory there is showing Level 1, and the crowns info box agrees, but the data that the flag borders use is the saved progress doesn't have any data so it showing level 0 there as it is the default.

i re-run chrome.storage.sync.get("progress", (data) => Object.keys(data.progress).forEach((tree) => console.log(`${tree} is at tree level ${data.progress[tree][data.progress[tree].length -1][1]}`))) 

and do not see any user with name "ak-s"

**Comment by ToranSharma** [comment] 2020-10-29 13:45
I think I might have worked it out.

There is a size limit to what you can store in the web extension storage API of 102400 bytes, and 8192 bytes per item (all the saved progress from all the trees is in one item)

There is a chance you have reached this limit.

If you run
```javascript
chrome.storage.sync.getBytesInUse(null, numBytes => console.log(`There are ${numBytes}B/${chrome.storage.sync.QUOTA_BYTES}B being used in total`));chrome.storage.sync.getBytesInUse("progress", numBytes => console.log(`There are ${numBytes}B/${chrome.storage.sync.QUOTA_BYTES_PER_ITEM}B being used in a single entry for the progress history`))
```
we will see it has been filled up...

**Comment by alexseyk** [comment] 2020-10-29 14:24
There are 9434B/102400B being used in total VM95:1 
There are 8192B/8192B being used in a single entry for the progress history

So how do i clean it ? besides my current data there are data with  my  old username, current username in old storage format (only target language not the base)  and data for my friends and followers(?)... not sure how the last got there.  

So someone with many languages to study will have similar issue ...

**Comment by ToranSharma** [comment] 2020-10-29 15:02
It is possible for you to clear it out yourself, it isn't straight forward, but I can send instructions if you want to do it.

I really need to rethink how and what I am keeping in the storage to stop this from happening. I will write some functions that will remove old data etc and include it in a patch when I can but it probably won't be today.

**Comment by alexseyk** [comment] 2020-10-29 16:39
Ok it surely can wait.
I uninstalled plugin. Cleaned browser data. Used Cleaner to be on safe side. Reinstalled plugin. It cleaned unnecessary data and got flag border to correct color. 

Now:

AKS-47laen is at tree level 3

There are 1283B/102400B being used in total
There are 45B/8192B being used in a single entry for the progress history

Hopefully it will update correctly when i get to L4 in latin (should be within a week)

**Comment by alexseyk** [comment] 2020-11-15 03:33
FYI: Upon reaching L4 flag border updated successfully

**Comment by ToranSharma** [comment] 2020-12-09 15:21
I think I should have resolved this issue in 7a0fe43.

After this change (which I will release as 1.3.41) when the progress history is updated, the progress for the current language is trimmed to only keep the entries so that there are at most 7 improvement events. This is then saved back into the storage API.

For example on my en->es tree, it cuts the number of progress entries from 77 to 10.

With only those 10 entries saved the storage situation looks like this:
```
There are 1474B/102400B being used in total
There are 246B/8192B being used in a single entry for the progress history
```

So I could have just over 30 trees with that many entries. It should therefore be exceedingly unlikely that a user will every get near the storage limit as before.

Let me know how yours looks after the update (and before for comparison if possbile) and I will close the issue.

**Comment by alexseyk** [comment] 2020-12-10 05:14
Mine gives 8 entries. It seems that I have re-installed plugin and "cleaned" all history settings. So there is no easy way to test. I guess i can change my user name several times to populate the history data storage, but as i understand you did not address this issue (i.e. user names vs. ID ) so far.  

There are 2097B/102400B being used in total
There are 858B/8192B being used in a single entry for the progress history

Since you trimming history to 10 items, will it affect tree (and XP) level predictions?
https://github.com/ToranSharma/Duo-Strength/issues/126

**Comment by ToranSharma** [comment] 2020-12-10 12:42
> Since you trimming history to 10 items, will it affect tree (and XP) level predictions?
> #126

While I have very slightly tweaked how the prediction's work based on this change, the prediction will not be adversely affected. As I am now only keeping the progress records that show 7 improvement events, the prediction algorithm now just uses all of the data available, which will be those last 7 improvement events. Before, I count back 7 entries from the end and used those to make the prediction. This change if anything should make the prediction more stable.

As a note 7 is pretty much an arbitrary choice of the number of improvements events to keep a record of. It does mean that if a user does progress contributing lessons every day, then the prediction will be based of off a rolling week's worth of improvement, which will match nicely with the crowns progress graph.


> I guess i can change my user name several times to populate the history data storage, but as i understand you did not address this issue (i.e. user names vs. ID ) so far.

Yes, I had neglected that part of the issue. The only solution I can think of is to cull the trees based off of when the last entry in the progress was. I am not sure what cutoff would be the best. It would need to be long enough that it doesn't delete the progress history for a user who does use a tree, but only infrequently.

Maybe something like 3 months should be long enough that if there has not been any new progress saved in that time, the tree is not being used so the entries can be deleted.

As you mention I could also change it so that the entries are saved by userID rather than username. I assume that the userID does not ever change, so this would be more stable and handle username changes seamlessly. If I were to make this change I would have to make a decision whether as to copy over the existing progress history to the new format, or just start over and let enough time elapse before the change mentioned above would remove the old format.

I make the first time cutoff change, and think about moving over to a userID based key for saving the progress history.

**Comment by ToranSharma** [comment] 2020-12-10 16:27
I will change to a a new format for the keys in the stored progress object to be user ID based:
```
old format
username+languageCode+baseCode
e.g.
ToranSharmaesen

new format
userId:baseCode->languageCode
e.g.
34200411:en->es
```
This should remove any username change issues, and it is a little clearer to read with the ordering of the language codes swapped and with the arrow to avoid ambiguity.

For the next few months I will keep in some code that will check for progress saved in the old format and transfer it to the new one, deleting the old. After 3 months of the new format the culling process will remove the old format anyway and this check can be removed eventually.

**Comment by ToranSharma** [comment] 2020-12-10 17:29
These changes were made in 4d790de.

I will shortly release these changes as part of v1.4.42

This command will list the trees saved and the date of the most recent entry
```javascript
chrome.storage.sync.get("progress", data => Object.entries(data.progress).forEach(([key,history]) => console.log(`${key} has ${history.length} entries, latest from ${(new Date(history[history.length -1][0])).toDateString()}`)));
```
my output
```
34200411:en->es has 10 entries, latest from Wed Dec 09 2020
34200411:en->fi has 1 entries, latest from Wed Dec 09 2020
34200411:en->sv has 1 entries, latest from Thu Dec 10 2020
LucyAllison1esen has 3 entries, latest from Sat Oct 17 2020
ToranSharmadeen has 1 entries, latest from Fri Oct 30 2020
ToranSharmaenes has 1 entries, latest from Wed Dec 09 2020
ToranSharmafren has 1 entries, latest from Thu Oct 29 2020
rpuluriandeen has 2 entries, latest from Fri Oct 30 2020
```

Note that you will have to change to each tree for the key to be changed to the new user ID based format.

**Comment by ToranSharma** [comment] 2021-01-07 18:56
This change is fully incorporated now. Note that the flag borders feature has now been changed to get the tree level of each of the users tree from a separate section of the storage API now in an object called treeLevels. The information is stored under the key format from above, based on the userID and languages codes. This information does not get wiped out after three months of no change. This means that any finished trees will keep their flag borders without the user needing to  revisit that tree to update the data.

**Closed by ToranSharma** 2021-01-07 18:56 UTC
Labels: bug
