### ISSUE TITLE
Not opening the lessons

### ISSUE THREAD

**Issue by wms33** [ToranSharma/Duo-Strength#51] opened 2020-03-22 19:13 UTC
When I use the extension, it will not let me start a new lesson a lot of the time. When I hover the mouse over the start lessons button it stays as the mouse rather than whiching to the hand and when I click on start lesson, nothing happens. When I disable the chrome extension it works fine again

**Comment by ToranSharma** [comment] 2020-03-23 13:16
Thanks for reporting this issue, I'll look into it.

Is this when you try to do a lesson in the normal way, i.e. scroll down the tree to find the skill you want, click on it and click start on the little popout bubble that appears below the skill?

**Comment by wms33** [comment] 2020-03-23 20:00
Yeap,  its scrolling down the tree, I can click on the bubble fine, its when I try to click start nothing happens, although sometimes it works. I can click on everything else fine eg tips, unlock etc, just having trouble with the start button.
Thanks so much

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by ToranSharma** [comment] 2020-03-24 15:41
Hi again,

I think I have found a way to reproduce this issue, or at least one that looks very similar to what you describe. What exactly happens when you try to click on the START button when there is no pointing hand cursor. Does the popout bubble disappear or does simply nothing happen.

The problem I have found appears to be that the general strengthen button is contained in a very wide box that is invisible but still covering other elements of the page. Here is a screenshot of the element, which I have added a border to:
![image](https://user-images.githubusercontent.com/4559968/77444572-eda15b00-6de3-11ea-8838-c3218fc555f8.png)

This is nothing to do with Duo Strength, and is true if the extension is disabled. You can see the impact of this box by trying to click on a skill that is underneath that box, it will have no response.

What Duo Strength does seem to impact is whether the popout bubble for a skill that has been click on is below or on top of that box. See these screenshots to illustrate that, for some reason that I cannot immediately work out, Duo Strength causes the popout bubble to be below this box, while ordinarily it would be on top of it.

Duo Strength enabled: 
![image](https://user-images.githubusercontent.com/4559968/77444957-630d2b80-6de4-11ea-9104-f025e85fd335.png)

Duo Strength disabled:
![image](https://user-images.githubusercontent.com/4559968/77445036-7ddfa000-6de4-11ea-859e-eaeebbb03f19.png)

Note that even the dumbbell icon for the general strengthen button is over the popout window when the window is small enough.

To reproduce this, scroll down so that the skill you want to click is near the bottom of the screen, preferable just above the general strengthen button. Then click on the skill so that the popout bubble appears. If the skill was sufficiently close to the bottom of the screen then the page will have to scroll up slightly to display the bubble in its entirety. However now the START button will be beneath this invisible box and not be able to be clicked.

If you could test this and confirm this is the issue that you are seeing it would be appreciated.

Thanks,

Toran

**Comment by ToranSharma** [comment] 2020-03-24 17:05
Also note I have submitted a bug report to Duolingo to fix the underlying problem.

**Comment by wms33** [comment] 2020-03-24 19:35
Ahh yes, that is exactly it, whenever any button in the pop up is inline with the weights symbol it doesnt work. Thats exactly the problem. When i scroll up a bit it then works.
Thanks
William

Sent from my iPhone

On 25/03/2020, at 04:41, Toran Sharma <notifications@github.com> wrote:

﻿

Hi again,

I think I have found a way to reproduce this issue, or at least one that looks very similar to what you describe. What exactly happens when you try to click on the START button when there is no pointing hand cursor. Does the popout bubble disappear or does simply nothing happen.

The problem I have found appears to be that the general strengthen button is contained in a very wide box that is invisible but still covering other elements of the page. Here is a screenshot of the element, which I have added a border to:
[image]<https://user-images.githubusercontent.com/4559968/77444572-eda15b00-6de3-11ea-8838-c3218fc555f8.png>

This is nothing to do with Duo Strength, and is true if the extension is disabled. You can see the impact of this box by trying to click on a skill that is underneath that box, it will have no response.

What Duo Strength does seem to impact is whether the popout bubble for a skill that has been click on is below or on top of that box. See these screenshots to illustrate that, for some reason that I cannot immediately work out, Duo Strength causes the popout bubble to be below this box, while ordinarily it would be on top of it.

Duo Strength enabled:
[image]<https://user-images.githubusercontent.com/4559968/77444957-630d2b80-6de4-11ea-9104-f025e85fd335.png>

Duo Strength disabled:
[image]<https://user-images.githubusercontent.com/4559968/77445036-7ddfa000-6de4-11ea-859e-eaeebbb03f19.png>

Note that even the dumbbell icon for the general strengthen button is over the popout window when the window is small enough.

To reproduce this, scroll down so that the skill you want to click is near the bottom of the screen, preferable just above the general strengthen button. Then click on the skill so that the popout bubble appears. If the skill was sufficiently close to the bottom of the screen then the page will have to scroll up slightly to display the bubble in its entirety. However now the START button will be beneath this invisible box and not be able to be clicked.

If you could test this and confirm this is the issue that you are seeing it would be appreciated.

Thanks,

Toran

**Comment by ToranSharma** [comment] 2020-03-25 15:06
I have just had a bit more of an investigate. I am not going to patch the underlying issue of this invisible box covering things as this is a duolingo bug and with any luck it will be patched at some point. I have however found the reason the Duo Strength is causing the popout bubbles to be below this box, rather than above, as it is without the extension.

This is now fixed in 9d64d22.

I am going to release this small patch as v1.2.8 so that you don't have to worry about scrolling up.

**Closed by ToranSharma** 2020-03-25 15:06 UTC

**Comment by ToranSharma** [comment] 2020-03-30 18:53
Note that the underlying issue has been fixed by Duolingo now. As such, skills at the bottom of the page can now be clicked on as expected.

The update has also caused a couple of issues that will be fixed in v1.2.9

**Comment by wms33** [comment] 2020-03-30 19:25
Hey Man
Thanks so much for all of that, keep up the great work.
William

Sent from my iPhone

On 31/03/2020, at 07:54, Toran Sharma <notifications@github.com> wrote:

﻿

Note that the underlying issue has been fixed by Duolingo now. As such, skills at the bottom of the page can now be clicked on as expected.

The update has also caused a couple of issues that will be fixed in v1.2.9
