### ISSUE TITLE
skills that need strengthening: practice or next lesson

### ISSUE THREAD

**Issue by alexseyk** [ToranSharma/Duo-Strength#35] opened 2020-01-29 09:38 UTC
Hi
When i do "skill strengthening" from the duome.eu website it goes to practise i.e. https://www.duolingo.com/skill/es/Pronouns/practice
If i do skill strengthening in your extension it goes to the next lesson in the skill (unless it is L5) i.e. https://www.duolingo.com/skill/es/Pronouns

This may or may not be desired function. i.e. if you wish to keep  your language tree (skill)  at a particular level. 

It was suggested on the forum tha practice exercises at  L4 are more difficult that at L5. Don't remember if it was   about individual skill practice or global (whole tree)

**Comment by ToranSharma** [comment] 2020-01-29 12:57
Hi @alexseyk,

I was not aware that duome always points to the practice url for the skill. The behaviour of the links in the needs strengthening list etc. are to match with the url that duolingo takes you to if you were to click on the skill manually and click the start/practice button.

I think I am happy with the current functionality, as if all the links were changed to practice, then no crowns progress would be made using Duo Strength. I think this would cause most users confusion, not be what they would want.

However, I can fairly easily add a option to change this behaviour, say at L4, or whenever the user chooses. This it probably the best solution as it will allow normal crown progress, which most users will expect, but also allow users that do not want to get their skills to L5 the option to still strengthen them at this harder level.

What do you think to this solution?

Do note however, that I think in a forum comment, someone from duolingo more or less said that the L5 content being easier than L4 is not intended behaviour on duolingo's part, so this may change in the future.

Toran

**Comment by alexseyk** [comment] 2020-01-29 15:27
Toran

On duome you have both options: to practice & to proceed to next lesson.
Functionality to practice individual skills ( at  levels less than 5 )  is only available   on duome.

It sounds great if i can  toggle between practice & progress modes! I like your solution.

For me practice (without progress) make sense since i study multiple languages ( and in reverse order)  and want to keep Trees at  a particular Level before i proceed to the next.

It would be interesting to know  profile of typical Duo student: how many languages and if reverse tree is attempted. Method of progress:  leveling  skill by skill, or opening whole tree and then leveling skills  and\or some combination of the two. 

Yes, i understand from  the forum posts that space repetition is broken and L5 / L4 practice is not as desired. As well as general negative feedback to reduced number of lessons required to progress to L5.
Alex

**Comment by alexseyk** [comment] 2020-01-30 03:31
suggestion: add **practice option** (link) to your **strength bar **
so if user clicks on the bar it goes to practice if user clicks on the skill icon it goes to normal lesson

**Comment by ToranSharma** [comment] 2020-01-30 18:54
Hi again Alex,

I have added the new option to select the lesson/practice behaviour in be74444. You can choose from "Lessons (Earn Crowns)", "Practice (Strengthen Only)" and "Lessons up to threshold" with a sub-option to change that threshold. This is how it looks in the options menu:

![Practice Type Options](https://toransharma.com/i/Practice%20Type%20Options.png)

I'll have a think about ways to implement a practice button for each skill. I suppose I could add it underneath the START button which can be relabelled to make it more clear that it starts a lesson. Something like this:

![New Practise Button on Skills](https://toransharma.com/i/Practise%20Button.png)

What do you think?

Toran

**Comment by alexseyk** [comment] 2020-01-31 10:20
i like it. You are the best !

**Comment by ToranSharma** [comment] 2020-02-04 14:56
The PRACTISE button has been added in b4e2208.

I think that is all for this issue, so I'll close it and merge the issue35 branch into the develop branch for inclusion in the next release.

**Closed by ToranSharma** 2020-02-04 14:56 UTC
