### ISSUE TITLE
'Cracked Skills List' not appearing

### ISSUE THREAD

**Issue by squirlrat** [ToranSharma/Duo-Strength#150] opened 2021-03-02 12:20 UTC
Since the latest update I am not seeing cracked skills listed at the top of my tree for French From English.  When I scroll down my tree I can see that I do have cracked skills.  If I switch to my English from French tree or my Esperanto From English tree the cracked skills list appears correctly, so I am pretty sure this isn't an issue with my settings.

(I have French to English trees on three different Duolingo accounts but am only seeing this bug on two of them)

**Comment by ToranSharma** [comment] 2021-03-02 13:31
Thanks for letting me know, I'll try have a see what could be going on. Strange that it is inconsistent across tree and accounts.

**Comment by ToranSharma** [comment] 2021-03-02 22:51
Unfortunately I haven not been able to reproduce this myself.
I have just released v2.0.1 which has a lot of fixes of small and one large bug. There is a change that this behaviour was the result of one of those.

Please let me know if it persists after the update. You can check your version number in the top right of the Duo Strength options popup window.

**Comment by squirlrat** [comment] 2021-03-03 12:48
I must apologise for the misleading title I originally gave this report.

I am now using v2.0.1
When I loaded my tree I could still only see the "skills that needed strengthening" list at the top of the page and not the "skills that are cracked" list. Turning 'Display Cracked Skills List' off and on again made no difference.  However when I turned 'Display Needs Strengthening List' off and back on the cracked skills list appeared as well as the needs strengthening list.  However the cracked skills list displays first, above the needs strengthening list!

**Comment by ToranSharma** [comment] 2021-03-03 13:32
No problem. Thanks for the extra information. I'll see if I can find out what is causing it not to be added.

The chaning ordering of the lists is a know thing that I will also try to fix.

**Comment by ToranSharma** [comment] 2021-03-04 18:45
This issue has been fixed in 2ff5050 as described in #156 which this turns out to be a the same as.

The French from English tree has one skill which has a url with an accented character, namely the grammar skill "Le gérondif". The é in this was not being handled properly when the skill was in your needs strengthening list. The resulting error was stopping execution and preventing the cracked skills list from displaying.

This is why it did display when you removed the needs strengthening list and re added it, as the error was then happening after the list was added.

The fix will be released shortly as part of v2.0.2.

**Closed by ToranSharma** 2021-03-04 18:45 UTC
Labels: bug
