### ISSUE TITLE
Suggestion: Focus on the lesson after finishing it

### ISSUE THREAD

**Issue by Origitalus** [ToranSharma/Duo-Strength#159] opened 2021-03-16 02:11 UTC
Hey, 
usually if one finishes a lesson, Duolingo shows this screen:
![image](https://user-images.githubusercontent.com/60040210/111245015-3dd08900-8604-11eb-9b4d-16b285d428a0.png)

But if I have startet a lesson via the Cracked Skills List (really nice feature btw) 
![image](https://user-images.githubusercontent.com/60040210/111245455-f1d21400-8604-11eb-8ede-6b60bf7db727.png)
then there is no aforementioned screen.

It's not really a hot button issue since I can just click the blue "open popup for..." button and start from there.

**Comment by ToranSharma** [comment] 2021-03-17 14:20
This is actually the intended behaviour - take the user back to where they came from.

If they went to a lesson from a link in a list at the top. Leave them at the top when they get out of the lesson. If they clicked on the start button in a skill's popout bubble, take them back there when done.

My thought process is that if you have say 5 things to address as per the lists at the top of the tree. you will want to go through them one by one. Once you have finished the first one, you will want to click on the next. Taking the user to somewhere other than the lists at the top after they have clicked one of the links would get in the way of the point of the lists - quick access without scrolling through the tree.

As you say the blue open skill popup button is there if you want to quickly go to a skill in the tree, so I don't see a reason to change this behaviour.

Given I don't think anything is amiss I'll close this issue.

Toran

**Closed by ToranSharma** 2021-03-17 14:20 UTC
