### ISSUE TITLE
hide text - partly not working 

### ISSUE THREAD

**Issue by alexseyk** [ToranSharma/Duo-Strength#57] opened 2020-04-07 03:19 UTC
Uncaught TypeError: Cannot read property 'getAttribute' of null
    at hideTranslationText (duoStrength.js:2268)
    at MutationObserver.childListMutationHandle (duoStrength.js:2591)

sometimes button to hide text is not shown and text is not hidden

**Comment by ToranSharma** [comment] 2020-04-07 12:43
I have seen that line cause errors and determined that it was caused by the screens with encouraging messages from duo, e.g. getting 10 questions correct in a row. I my experience the error would have no impact on subsequent questions, so I have left it unpatched in the current releases.

The error has been prevented in fd286698f0d393b13d7234765eefcd1735136de6.

This fix checks to see if the question container element's first child exists. This check shows that there are no children of the question container element, i.e. no question box on the page at that time.

Here is a screenshot of the error happening where I intentionally failed a few questions in a row to trigger an encouragement message:

![image](https://user-images.githubusercontent.com/4559968/78669603-6e785080-78d4-11ea-89ee-d67f118819df.png)


As above, as far as I know this error, doesn't prevent any further hiding of question texts, as the function is called asynchronously, when a new question appears. This may not be the case, and I may have simply have not noticed.

If you get this error, either not from an encouragement message, or if after an encouragement message a subsequent question is not hidden correctly, please let me know.

**Comment by ToranSharma** [comment] 2020-04-07 13:18
I should say that the fix is in the development branch, ready for v1.3

**Comment by alexseyk** [comment] 2020-04-09 01:42
I am  waiting for v1.3 :) My experience with this bug is in the bonus skills En -> Es. I don't observe any difference after a motivational message appears.  I don't have many golden (L5 skills) so i can not say if such behavior is specific to bonus skills or to L5 practice.

**Comment by ToranSharma** [comment] 2020-04-09 15:12
Hmm, most of my testing is done on En->Es but I have not bought any bonus skills. I will test to see if I  notice any issues with the text hiding.

I think I'll leave this for the time being. As said I have patched the issue causing the error on encouragement messages. I will see if I can notice any time where the text hiding is not working after v1.3 is released.

**Comment by ToranSharma** [comment] 2020-04-12 19:04
As a note, v1.3 has now been released.

**Comment by alexseyk** [comment] 2020-04-15 06:48
Still the same for bonus skills. Also for golden bonus skills  "practice" button is replaced with "practise". Just a visual thing. I guess since they are L1 and not L5 like normal skills.

**Comment by ToranSharma** [comment] 2020-04-15 15:24
Okay, I will look into this text hiding issue in bonus and golden skills. It seems strange that these lessons would be any different in terms of causing an error with this feature.

The practise button on bonus skills is something I missed, I'll fix that by making the practise button feature ignore bonus skills that are at L1 like it does from noraml skills that are L5.

**Comment by ToranSharma** [comment] 2020-04-15 16:04
Practise button has been removed from bonus skills in 9940dda. Bonus skills are either L0 and therefore unfinished so no practise button should be added or L1 and golden, in which case you can only practise it so the existing button does that.

**Comment by ToranSharma** [comment] 2020-05-01 14:57
> Still the same for bonus skills.

I am testing this now on an En->Es tree, on the "Idioms and Proverbs"  bonus skill, which is at L1. As far as I can see the text hiding feature is working. The only issue was that it was hiding sentences that had a word highlighted in yellow to indicate that it is new. That was fixed in b01169b and affected all skills.

I tested after a duo encouragement message and the error message (that was fixed in v1.3.0 as mentioned above) doesn't appear. Subsequent questions seem to be working too.

Similarly I have tested L5 skills in a En->Sv tree and text hiding seems okay there too.

Are you still seeing this behaviour, if so can you provide any more information or another screenshot of any error messages you are getting after you notice it happen.

You said in your original post that:
> sometimes button to hide text is not shown and text is not hidden

If it is still happening is it just sometimes, is there a concrete way to reproduce it?

Thanks,

Toran

**Comment by alexseyk** [comment] 2020-05-02 01:35
Hi
So I tried it yesterday and it seems everything was working.. today - it is not ;( 
Now i have ver 1.3.7. I am testing on En->Es Idioms skill  L1 (golden) too. 

Yes it seems that it is not hiding sentences with yellow (new) words 
There are no errors in the console
<img width="1178" alt="Screen Shot 2020-05-02 at 08 33 24" src="https://user-images.githubusercontent.com/60418150/80852061-a5315480-8c4f-11ea-8b4b-ba1425f12dee.png">

I think you can call it a feature.. it makes certain cense not to hide sentences with new words:)

**Comment by ToranSharma** [comment] 2020-05-02 12:01
Yes this has always been a feature I added. Imagine you are learning a new skill with new words you haven't seen before and need to learn it, it would be very unhelpful if they were blurred out.

It was actually a bug that must have been introduced after a recent duolingo change that was causing these sentences to be hidden, despite the new words.

It is a duolingo issue that even if you have completed the bonus skills, some of the words come up as new no matter how many times you have seen them before.

I hope that clarifies things a little.

Toran

**Closed by ToranSharma** 2020-05-02 12:01 UTC
