### ISSUE TITLE
Skill strengths not updating and not listed at top

### ISSUE THREAD

**Issue by nicisfurst** [ToranSharma/Duo-Strength#1] opened 2019-01-11 01:57 UTC
Hey!
_First of all I just wanted to say i love this extension and although simple, very helpful._

To my issue, on my German tree, 2 skills (Intro and Food 1) are both at 0% which leads me to the first issue. These 2 skills are not listed at the top of the page as skills which require strengthening. The second issue is that when I go to practice the skill and return back to the tree, the practiced skill is still on 0% and is not updated. Bellow I have provided a screenshot to show you what I mean. I hope you can fix this so that myself and others can use this extension to its full ability.

Thanks.

![capture](https://user-images.githubusercontent.com/29367812/51008561-67af4080-15a0-11e9-953c-a5076b6d6649.PNG)

**Comment by ToranSharma** [comment] 2019-01-11 23:19
Hi nicisfurst,

Thanks for the support, I'm happy it is useful for you.

In regards to your issue, I have a possible idea as to what could be causing the behaviour you are seeing. I'll check it out when I can.

Thanks,

Toran

**Comment by nicisfurst** [comment] 2019-01-11 23:22
> Hi nicisfurst,
> 
> Thanks for the support, I'm happy it is useful for you.
> 
> In regards to your issue, I have a possible idea as to what could be causing the behaviour you are seeing. I'll check it out when I can.
> 
> Thanks,
> 
> Toran

No rush
I would help you on this but unfortunately I don't know much JS

**Comment by nicisfurst** [comment] 2019-01-11 23:30
> Hi nicisfurst,
> 
> Thanks for the support, I'm happy it is useful for you.
> 
> In regards to your issue, I have a possible idea as to what could be causing the behaviour you are seeing. I'll check it out when I can.
> 
> Thanks,
> 
> Toran

No Rush

UPDATE: I tried this on my Japanese skill and everything is working perfectly. My guess is that its something to do with skills being gold as in the German tree, the skills not at 100% were gold BUT in the Japanese tree, the skills that are not 100% are NOT gold. So yeh, my guess is something to do with the skill being gold.

**Comment by ToranSharma** [comment] 2019-01-12 12:44
Just done a bit of investigation and my theory was correct.

It was putting 0% strength on those two skills as it thought they were the bonus skills that you can buy in the store. The reason it thought they are bonus skills is that I never detect if the user has bought those skills and I was inputting them into the tree naïvely based off of where they go in the spanish tree.

It shouldn't be too difficult to fix these things. I'll push out the fixes in the next update which should be later today.

**Comment by ToranSharma** [comment] 2019-01-12 16:48
Hi @nicisfurst ,

Just finished testing a rework of the way I handle bonus skills which I am 99% sure what caused your problem. Attached to this comment is a zip with a test version of the extension for you to try out.

The steps to run the test version are as follows:
1) unzip the attached .zip file into its own folder somewhere.
2) go to chrome://extensions
3) find Duo Strength (version 1.0.2) and turn it off with the switch in the bottom right.
4) Switch on developer mode in the top right of the window
5) click load unpacked in the top left of the window
6) navigate to where you unzipped the file and select the folder you unzipped the contents, and click okay.

This should add version 1.0.3 of Duo Strength to your chrome. Reload duolingo and see if the issue is fixed.

Please let me know how you get on with this. If everything is fixed then I'll push out this version for everyone. it also contains a few other fixes I had been working on over the last few days.

Thanks,

Toran


NB having an unpacked extension enabled with chrome in developer mode gets quite annoying if you open and close chrome due to a warning it gives on start up so after testing feel free to turn off or remove the new extension and re enable the old one.

[Duo-Strength beta for nicisfurst.zip](https://github.com/ToranSharma/Duo-Strength/files/2752257/Duo-Strength.beta.for.nicisfurst.zip)

**Comment by ToranSharma** [comment] 2019-01-12 20:54
Just a quick update to this, I thought I would test it out myself using your duolingo strength data. I just forced the username to be nicisfurst but it is displaying on my swedish tree so the layout is different. Here is a screen shot of the new code vs the old:
![nicisfurst data old vs new](https://user-images.githubusercontent.com/4559968/51078378-18563680-16ac-11e9-91e4-28ccdfeb4916.PNG)

As you can see there two skills that were at 0% are now at 100% which is correct based off of duome.eu. I hope you see the same results your self so I can push this out.

**Comment by nicisfurst** [comment] 2019-01-12 21:53
Good News!

The code seems to work.
It's weird that Duolingo sees those skills as bonus's as i haven't bought any but anyway, it works which is great! Let me know when Duo Strength is released the the public version so I can switch back to that. 

Thanks anyway!

**Comment by ToranSharma** [comment] 2019-01-12 22:04
Thanks for testing it out for me.

The strange behaviour is totally down to me handling bonus skills poorly and not quite understanding how the data was treating them. It seems you get the info about them even if you have not bought the bonus skills yet. That is all sorted out now, so I'll go ahead and close this issue and release the new version. It should be up in the next few minutes and auto update itself within a couple of hours. If you are done with duolingo for today, its probably easiest to remove the beta version and enable the old one if you haven't already.

Cheers,

Toran

**Closed by ToranSharma** 2019-01-12 22:04 UTC

**Comment by nicisfurst** [comment] 2019-01-13 02:43
Just updated and works perfectly, Thanks!

I encourage you to continue working on this project, adding a whole range of useful features. Unfortunately I don't know js so cant really help you there but yeah, I cant wait to see what else you implement!
