### ISSUE TITLE
It stopped working since yesterday 

### ISSUE THREAD

**Issue by alexseyk** [ToranSharma/Duo-Strength#80] opened 2020-06-03 03:19 UTC
Uncaught (in promise) TypeError: Cannot read property 'href' of null
    at init (duoStrength.js:4398)
    at document.body.onload (duoStrength.js:4520)

UPD: Mysteriously extension  works after i visit setting page .

**Comment by ToranSharma** [comment] 2020-06-09 14:25
Hi, sorry for the slow reply, I haven't been getting email notifications for a over a week so I have only just seen these recent issues.

The href error is caused by the Duo Strength failing to location a place that it can scrape your username from the page.

v1.3.11 released on 2020-05-18 is made to update how this was done after duolingo removed the place that the username was being taken from.

Currently, it is being taken from the last element of this array:
```` javascript
document.querySelector(`[href^="/profile/"]`).href.split("/")
````
This takes the first element in the page that has an href attribute that points to a profile page, gets that link, and takes the part of the final slash, which should be the username.

In particular on the learn page, this is taken from the link in the top right of the achievements box in the side bar. Pages where there is no element that points to profile page will have an error, e.g. the words page.

I should probably add a check for the existence of such an element and stop the execution of the script if it is not found, awaiting a page change that does contain it.

**Comment by ToranSharma** [comment] 2020-06-09 14:26
If you getting this error on the learn page, that means that there is no place to take the username. This is possibly the case for a user that has all the achievements, but I don't know what this looks like as I still have some league achievements unearned.

**Comment by ToranSharma** [comment] 2020-06-09 15:08
I have added a check for the existence of an element that contains a link to the users profile page in b4ad266. If such an element is not found, this fact is send to the console as an error.

**Comment by ToranSharma** [comment] 2020-06-09 15:44
> UPD: Mysteriously extension works after i visit setting page .

Note that there is a link to the users profile on the settings page so this would set the username, The extension would then work if going to a page without a place to pull the username from.

**Comment by alexseyk** [comment] 2020-06-10 04:59
Yes, about that time I obtained the last achievement and also achievement table disappeared from the learn page. .

Attached is my "learn" web page. Hopefully you can figure something out.
profile name = 'AKS-47'

I can see my profile in friends box but it disappears too when profile is made private, also not sure how you can figure out which of the friends profiles is the current user. Except for the golden circle...

Could it be that 
`<script type="text/javascript" name="duo-profile">(function f() {`
gets the profile  via  
`var p_reg = new RegExp("^/(profile/)?([a-zA-Z0-9._-]+)$"); `
??

I understand that you need profile name to make extension work, but you have features that do not require it. Can you enable them ? i.e. links to practice, checkpoint tests, words, etc...

[Archive.zip](https://github.com/ToranSharma/Duo-Strength/files/4756156/Archive.zip)

**Comment by ToranSharma** [comment] 2020-06-10 11:42
Thanks for the files, I'll see if I can find some more universal way to get a the username for any user. Note this wasn't an issue before the Duolingo update around 2020-05-18, there was a consistent link to the profile in the top bar from the mobile layout, but that was removed for some reason.

You are right that some features do not need the user's extended profile file, and so can be used without the username.

I will have a look to see if I can find a solution first, and if there isn't anything obvious I will make the modifications to run those features regardless of having the file or not.

> Could it be that
> `<script type="text/javascript" name="duo-profile">(function f() {`
> gets the profile via
> `var p_reg = new RegExp("^/(profile/)?([a-zA-Z0-9._-]+)$");`

I am not sure where you are getting this code snippet from, that regular expression would match urls that point to the profile page.

**Comment by ToranSharma** [comment] 2020-06-10 23:20
v1.3.13 has now be released with this fix. It may take a few hours to be approved on Chrome, but is available now on Firefox and Opera

If you could confirm that it has solved this issue that would great!

**Comment by alexseyk** [comment] 2020-06-11 03:10
I downloaded code from GitHub and loaded it  in chrome as unpacked extension. At first glance it works!

**Comment by ToranSharma** [comment] 2020-06-11 11:21
Great, as always let me know of any issues, but this *should* be fairly robust.

**Closed by ToranSharma** 2020-06-11 11:21 UTC
